pipeline {
    agent any 
    stages {
    tools { 
        maven 'Maven 3.6.0' 
        jdk 'jdk8' 
    }
        stage('Build') { 
            steps {           
                zsh 'mvn clean install'
               
            }
        }
        
    }
}
