pipeline {
    agent any 
    tools { 
        maven 'M3' 
        jdk 'JAVA_HOME' 
    }
    stages { 
        stage('Build') { 
            steps { 
                sh 'cd DateTimeCalculator/date-time-calculator/'      
                sh 'mvn clean install'
               
            }
        }
        
    }
}
